### ISSUE TITLE
Publish utils package to pkg.go.dev

### ISSUE THREAD

**Issue by salaheldinsoliman** [jlvandenhout/contracts#1]
This can really help in: https://github.com/iotaledger/iota-wiki/issues/1451
Where a lot of solidity contracts would be moved to the wasp repo, and tests added for each. 
I think it just needs a `release` to be published? 
@lucas-tortora @Dr-Electron WDYT?

**Comment by lucas-tortora** [comment]
Sounds good to me. Though, if we're going to publish it we should move it from a personal repo to an iotaledger repo

**Comment by Ginowine** [comment]
Hi @salaheldinsoliman, can you write a description for this package, what it does, and explain how we can use it in the move Solidity code to the Wasp repo tasks?

**Comment by salaheldinsoliman** [comment]
@Ginowine Hi Gino,
I took @jlvandenhout 's work and tuned it a bit, as a lot of `Solo` utils was added recently. It would make more sense to use the example here:
https://github.com/iotaledger/wasp/pull/3446/files 
As this makes use of what Solo currently offers.

**Comment by Ginowine** [comment]
Thanks. This new repo is clear and has fewer files.

**Comment by salaheldinsoliman** [comment]
yes, as most of @jlvandenhout 's util was later introduced in `evmtest` and `wasp/util`. 
@jlvandenhout Did you introduce `util` there yourself?

**Comment by jlvandenhout** [comment]
The utils in this repo are written by myself, partially based on what was, and probably more importantly what was not, available back then in the Wasp repo. With the recent changes to the Wasp repo, I guess it makes more sense to actually use what is in the Wasp repo and improve that where necessary. Feel free to close this if you agree.

**Comment by salaheldinsoliman** [comment]
Yup, closing this as the current `util` in `wasp` suffices what is needed for testing.
